# Generated by Django 5.2.8 on 2025-12-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('affCase', models.JSONField()),
                ('affRebuttal', models.JSONField()),
                ('affSummary', models.JSONField()),
                ('affFinalFocus', models.JSONField()),
                ('negCase', models.JSONField()),
                ('negRebuttal', models.JSONField()),
                ('negSummary', models.JSONField()),
                ('negFinalFocus', models.JSONField()),
            ],
        ),
    ]
