# Generated by Django 5.2.8 on 2025-12-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseFlow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='affCase',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='affFinalFocus',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='affRebuttal',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='affSummary',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='negCase',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='negFinalFocus',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='negRebuttal',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='negSummary',
            field=models.JSONField(blank=True),
        ),
    ]
