# Generated by Django 5.2.8 on 2025-12-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseFlow', '0002_alter_flow_affcase_alter_flow_afffinalfocus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='affCase',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='affFinalFocus',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='affRebuttal',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='affSummary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='negCase',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='negFinalFocus',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='negRebuttal',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='negSummary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
