# Generated by Django 5.2.8 on 2025-12-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseFlow', '0003_alter_flow_affcase_alter_flow_afffinalfocus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
